# Generated by Django 2.2.4 on 2020-10-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(max_length=255),
        ),
    ]
